spring:
  application:
    name: oidc-client-backend

server:
  port: 8081
  servlet:
    context-path: /

oidc:
  server:
    url: http://localhost:8080
    token-endpoint: /oidc/token
    userinfo-endpoint: /oidc/userinfo
  client:
    id: my-app
    secret: secret123
    redirect-uri: http://localhost:8081/callback
    scope: openid profile email

jwt:
  secret: this-is-a-very-secret-key-that-should-be-at-least-256-bits-long-for-hs256-algorithm

logging:
  level:
    root: INFO
    com.oidc: DEBUG
